"""Task Plan Schema for RegTrust-RAG.

Defines the structured execution plans generated by Task Planner for DOMAIN_QA queries.
Adheres strictly to the 6 business task types:
  1. TABLE_LOOKUP: Retrieve explicit target data points from a table
  2. TABLE_COMPARE: Compare multiple table candidates/indicators (MAX, MIN, SORT)
  3. TABLE_CALCULATION: Extract multiple operands from tables and execute calculations
  4. FACT_SINGLE_CHOICE: Single-choice verification with text claims
  5. FACT_MULTI_CHOICE: Multi-choice verification with required correct count and sub-claims
  6. DIRECT_FACT_QA: Direct regulatory facts, thresholds, compliance, and procedure questions
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Literal


@dataclass(slots=True)
class TableSource:
    """Source table information extracted from query."""
    file_name: str | None = None
    sheet_name: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "file_name": self.file_name,
            "sheet_name": self.sheet_name,
        }


@dataclass(slots=True)
class TableTarget:
    """Explicit cell/column/row coordinate target for TABLE_LOOKUP."""
    row: str | None = None
    column: str | None = None
    indicator: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "row": self.row,
            "column": self.column,
            "indicator": self.indicator,
        }


@dataclass(slots=True)
class TableCandidate:
    """Candidate indicator for TABLE_COMPARE."""
    label: str
    target: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "label": self.label,
            "target": self.target,
        }


@dataclass(slots=True)
class TableOperand:
    """Operand coordinate for TABLE_CALCULATION."""
    name: str
    row: str | None = None
    column: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "row": self.row,
            "column": self.column,
        }


@dataclass(slots=True)
class SourceConstraints:
    """Constraints on documents, clauses, and institutions for FACT QA."""
    document_name: str | None = None
    article_number: str | None = None
    institution_type: str | None = None
    regulator: str | None = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {}
        if self.document_name:
            d["document_name"] = self.document_name
        if self.article_number:
            d["article_number"] = self.article_number
        if self.institution_type:
            d["institution_type"] = self.institution_type
        if self.regulator:
            d["regulator"] = self.regulator
        return d or {"document_name": None}


@dataclass(slots=True)
class ChoiceOption:
    """Structured option for FACT_SINGLE_CHOICE / FACT_MULTI_CHOICE."""
    label: str
    claim: str
    sub_claims: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "label": self.label,
            "claim": self.claim,
        }
        if self.sub_claims:
            d["sub_claims"] = self.sub_claims
        return d


@dataclass(slots=True)
class TaskPlan:
    """Structured execution plan output by Task Planner."""
    task_type: str
    question: str = ""
    # Table related fields
    source: TableSource | None = None
    scope: str | None = None
    targets: list[TableTarget] = field(default_factory=list)
    candidates: list[TableCandidate] = field(default_factory=list)
    operation: str | None = None
    expression: str | None = None
    operands: list[TableOperand] = field(default_factory=list)
    options: dict[str, str] | list[ChoiceOption] = field(default_factory=dict)
    # Fact choice related fields
    source_constraints: SourceConstraints | None = None
    choice_mode: str | None = None
    required_correct_count: int | None = None
    # Direct fact related fields
    query_keywords: list[str] = field(default_factory=list)
    need_clarification: bool = False
    clarification_reason: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize into clean, spec-compliant JSON dict."""
        t = self.task_type
        if t == "TABLE_LOOKUP":
            res: dict[str, Any] = {
                "task_type": "TABLE_LOOKUP",
                "source": self.source.to_dict() if self.source else {"file_name": None, "sheet_name": None},
                "targets": [t_item.to_dict() for t_item in self.targets],
            }
            if self.scope:
                res["scope"] = self.scope
            if self.options and isinstance(self.options, dict):
                res["options"] = self.options
            res["need_clarification"] = self.need_clarification
            return res

        elif t == "TABLE_COMPARE":
            return {
                "task_type": "TABLE_COMPARE",
                "source": self.source.to_dict() if self.source else {"file_name": None, "sheet_name": None},
                "operation": self.operation or "MAX",
                "scope": self.scope,
                "candidates": [c.to_dict() for c in self.candidates],
                "need_clarification": self.need_clarification,
            }

        elif t == "TABLE_CALCULATION":
            res = {
                "task_type": "TABLE_CALCULATION",
                "source": self.source.to_dict() if self.source else {"file_name": None, "sheet_name": None},
                "operation": self.operation or "SUBTRACT",
                "expression": self.expression or "",
                "operands": [op.to_dict() for op in self.operands],
            }
            if self.options and isinstance(self.options, dict):
                res["options"] = self.options
            res["need_clarification"] = self.need_clarification
            return res

        elif t == "FACT_SINGLE_CHOICE":
            opts: list[dict[str, Any]] = []
            if isinstance(self.options, list):
                opts = [o.to_dict() if isinstance(o, ChoiceOption) else o for o in self.options]
            return {
                "task_type": "FACT_SINGLE_CHOICE",
                "source_constraints": self.source_constraints.to_dict() if self.source_constraints else {"document_name": None},
                "choice_mode": "SINGLE",
                "options": opts,
                "need_clarification": self.need_clarification,
            }

        elif t == "FACT_MULTI_CHOICE":
            opts = []
            if isinstance(self.options, list):
                opts = [o.to_dict() if isinstance(o, ChoiceOption) else o for o in self.options]
            return {
                "task_type": "FACT_MULTI_CHOICE",
                "source_constraints": self.source_constraints.to_dict() if self.source_constraints else {"document_name": None},
                "choice_mode": "MULTI",
                "required_correct_count": self.required_correct_count or 2,
                "options": opts,
                "need_clarification": self.need_clarification,
            }

        else:  # DIRECT_FACT_QA
            return {
                "task_type": "DIRECT_FACT_QA",
                "source_constraints": self.source_constraints.to_dict() if self.source_constraints else {"document_name": None},
                "query_keywords": self.query_keywords,
                "need_clarification": self.need_clarification,
            }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskPlan:
        """Construct a TaskPlan dataclass from serialized JSON dictionary."""
        if not isinstance(data, dict):
            return cls(task_type="UNKNOWN")
        task_type = data.get("task_type", "DIRECT_FACT_QA")
        source = None
        if "source" in data and isinstance(data["source"], dict):
            source = TableSource(
                file_name=data["source"].get("file_name"),
                sheet_name=data["source"].get("sheet_name"),
            )
        targets = []
        for t_item in data.get("targets", []):
            if isinstance(t_item, dict):
                targets.append(
                    TableTarget(
                        row=t_item.get("row"),
                        column=t_item.get("column"),
                        indicator=t_item.get("indicator"),
                    )
                )
            elif isinstance(t_item, TableTarget):
                targets.append(t_item)
        candidates = []
        for c_item in data.get("candidates", []):
            if isinstance(c_item, dict):
                candidates.append(
                    TableCandidate(
                        label=c_item.get("label", ""),
                        target=c_item.get("target", ""),
                    )
                )
            elif isinstance(c_item, TableCandidate):
                candidates.append(c_item)
        operands = []
        for op in data.get("operands", []):
            if isinstance(op, dict):
                operands.append(
                    TableOperand(
                        name=op.get("name", ""),
                        row=op.get("row"),
                        column=op.get("column"),
                    )
                )
            elif isinstance(op, TableOperand):
                operands.append(op)
        source_constraints = None
        if "source_constraints" in data and isinstance(data["source_constraints"], dict):
            source_constraints = SourceConstraints(
                document_name=data["source_constraints"].get("document_name"),
                article_number=data["source_constraints"].get("article_number"),
            )
        options = data.get("options", {})
        if isinstance(options, list):
            options = [
                ChoiceOption(
                    label=o.get("label", ""),
                    claim=o.get("claim", ""),
                    sub_claims=o.get("sub_claims", []),
                )
                if isinstance(o, dict)
                else o
                for o in options
            ]
        return cls(
            task_type=task_type,
            question=data.get("question", ""),
            source=source,
            scope=data.get("scope"),
            targets=targets,
            candidates=candidates,
            operation=data.get("operation"),
            expression=data.get("expression"),
            operands=operands,
            options=options,
            source_constraints=source_constraints,
            choice_mode=data.get("choice_mode"),
            required_correct_count=data.get("required_correct_count"),
            query_keywords=data.get("query_keywords", []),
            need_clarification=data.get("need_clarification", False),
            clarification_reason=data.get("clarification_reason"),
        )
