"""Multi-target Retrieval Engine for RegTrust-RAG.

Executes targeted, discrete retrieval for each task generated by Task Planner:
  - TABLE_COMPARE: Discretely searches for every candidate indicator
  - TABLE_CALCULATION: Discretely extracts every mathematical operand
  - FACT_SINGLE_CHOICE / FACT_MULTI_CHOICE: Discretely retrieves evidence for each option claim and sub-claim
  - TABLE_LOOKUP: Targeted table coordinate retrieval
  - DIRECT_FACT_QA: Targeted regulatory fact retrieval

Adheres strictly to the user requirement:
  - Input: {"retrieval_tasks": [{"task_id": "T1", "target": "", "source_constraints": {}}]}
  - Output: {"retrieval_results": [{"task_id": "T1", "status": "SUCCESS", "evidence": []}]}
  - Avoids naive TopK inflation; executes deterministic multi-target retrieval.
"""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path
from dataclasses import replace
from typing import Any, Sequence

from app.indexing.index_reader import KnowledgeBaseReader, _row_to_search_result
from app.retrieval.table_evidence import table_metric_aliases
from app.schemas.chunk_schema import SearchResult, SourceInfo
from app.schemas.multi_target_retrieval_schema import (
    MultiTargetRetrievalResponse,
    TargetRetrievalResult,
    TargetRetrievalTask,
)
from app.schemas.task_plan_schema import TaskPlan
from app.utils.logger import get_logger
from app.utils.paths import resolve_path

logger = get_logger("app.retrieval.multi_target")

MULTI_TARGET_EVIDENCE_PER_TASK = 2
FACT_CHOICE_EVIDENCE_PER_TASK = 4
YEAR_TOKEN_RE = re.compile(r"(?<!\d)(?:19|20)\d{2}(?!\d)")


def _normalize_month_tokens(value: str) -> str:
    """Canonicalize Chinese month labels so ``8月`` and ``08月`` match."""
    return re.sub(
        r"((?:19|20)\d{2})年(0?[1-9]|1[0-2])月",
        lambda match: f"{match.group(1)}年{int(match.group(2))}月",
        value,
    )


def _normalize_document_name(value: str | None) -> str | None:
    """Remove common file-format suffixes before applying title filters."""
    if not value:
        return value
    name = str(value).strip()
    name = re.sub(r"\s*[（(]\s*(?:PDF|DOCX?|XLSX?)\s*[）)]\s*", "", name, flags=re.I)
    name = re.sub(r"\.(?:pdf|docx?|xlsx?)$", "", name, flags=re.I)
    return name.strip() or None


def _canonical_title(value: str | None) -> str:
    """Canonicalize title variants for matching user labels to KB titles."""
    if not value:
        return ""
    name = _normalize_document_name(value) or ""
    name = _normalize_month_tokens(name)
    name = re.sub(r"[\s\u3000\-_—]+", "", name)
    name = name.replace("（", "(").replace("）", ")")
    # Year may appear at either end: 2023年Foo（季度） vs Foo(季度)(2023年)
    years = re.findall(r"(?:19|20)\d{2}年", name)
    name = re.sub(r"(?:19|20)\d{2}年", "", name)
    name = name.replace("(", "").replace(")", "")
    return name + "".join(years)


def _document_match_key(value: str | None) -> str:
    """Normalize attachment labels without weakening the eventual doc_id filter."""
    name = _canonical_title(value)
    name = re.sub(
        r"^附件(?:\s*[一二三四五六七八九十百0-9]+)?\s*[:：、.．-]*",
        "",
        name,
    )
    name = re.sub(r"[《》〈〉:：、,，.。]", "", name)
    # Source attachment titles often include a structural 的 that question
    # labels omit, e.g. "负债评估的折现率曲线" vs "负债评估折现率曲线".
    return name.replace("的", "").replace("版", "")


def _document_filter_candidates(document_name: str | None) -> list[str]:
    """Build tolerant title/path tokens for incomplete KB title metadata."""
    if not document_name:
        return []
    normalized = _normalize_document_name(document_name) or document_name
    tokens = [normalized, str(document_name)]
    # The attachment title may be a longer notice containing the requested
    # regulation name, while chunks may store only a truncated title. Include
    # the distinctive regulation phrase as an additional token.
    for marker in ("办法", "指引", "通知", "规定", "条例"):
        pos = normalized.find(marker)
        if pos >= 0:
            tokens.append(normalized[: pos + len(marker)])
            break
    return list(dict.fromkeys(t for t in tokens if t))


def _find_document_ids(db_path: Path | str, document_name: str | None) -> list[str]:
    """Resolve a user document label to IDs using title, path and metadata.

    Some imported PDFs have truncated ``chunks.title`` values, while their
    complete attachment name remains available in ``local_path``. Resolving
    IDs first lets retrieval apply an exact ``doc_id`` filter instead of
    falling back to unrelated documents.
    """
    if not document_name:
        return []
    p = resolve_path(db_path)
    if not p.exists():
        return []
    tokens = _document_filter_candidates(document_name)
    if not tokens:
        return []
    # Prefer the authoritative parsed-document manifest.  It preserves the
    # complete attachment title even when SQLite title/path fields were saved
    # with truncated or mojibake text.
    manifest_candidates = [
        resolve_path("data/parsed/meta/doc_meta.jsonl"),
        resolve_path("data/parsed/meta/generated_manifest.jsonl"),
    ]
    wanted = _document_match_key(document_name)
    manifest_scores: dict[str, int] = {}
    for manifest in manifest_candidates:
        if not manifest.exists():
            continue
        try:
            for line in manifest.read_text(encoding="utf-8", errors="ignore").splitlines():
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                fields = [
                    row.get("attachment_title"), row.get("title"),
                    row.get("source_page_title"), row.get("file_name"),
                    row.get("local_path"),
                ]
                score = 0
                for idx, value in enumerate(fields):
                    if not value:
                        continue
                    candidate = _document_match_key(str(value))
                    if not wanted or not candidate:
                        continue
                    if candidate == wanted:
                        score = max(score, 100 - idx)
                    elif wanted in candidate:
                        score = max(score, 70 - idx)
                    elif candidate in wanted:
                        score = max(score, 40 - idx)
                doc_id = row.get("doc_id")
                if doc_id and score:
                    manifest_scores[str(doc_id)] = max(manifest_scores.get(str(doc_id), 0), score)
        except Exception:
            continue
    if manifest_scores:
        return [doc_id for doc_id, _ in sorted(manifest_scores.items(), key=lambda item: item[1], reverse=True)]

    conn = sqlite3.connect(p)
    try:
        ids: list[str] = []
        for token in tokens:
            like = f"%{token}%"
            rows = conn.execute(
                """SELECT DISTINCT doc_id FROM chunks
                   WHERE title LIKE ? OR local_path LIKE ? OR metadata_json LIKE ?""",
                (like, like, like),
            ).fetchall()
            for row in rows:
                if row[0] and row[0] not in ids:
                    ids.append(str(row[0]))
        return ids
    finally:
        conn.close()


def _preferred_document_ids(db_path: Path | str, document_name: str | None) -> list[str]:
    """Return the primary document plus same-family attachments.

    For a regulation title, the main PDF should rank first; attachments are
    retained only when they share the same parsed document family.
    """
    ids = _find_document_ids(db_path, document_name)
    if not ids:
        return []
    if len(ids) == 1:
        return ids
    p = resolve_path(db_path)
    conn = sqlite3.connect(p)
    try:
        placeholders = ",".join("?" for _ in ids)
        rows = conn.execute(
            f"SELECT doc_id, MIN(chunk_type='clause') FROM chunks WHERE doc_id IN ({placeholders}) GROUP BY doc_id",
            ids,
        ).fetchall()
        # Clause-bearing main documents precede spreadsheet-only attachments.
        clause_ids = [str(r[0]) for r in rows if r[1]]
        rest = [doc_id for doc_id in ids if doc_id not in clause_ids]
        return clause_ids + rest
    finally:
        conn.close()


def find_matching_table_titles(
    db_path: Path | str,
    file_name: str | None,
    sheet_name: str | None = None,
) -> list[str]:
    """Find actual matching table titles in metadata.db supporting quarter synonyms and naming variants."""
    if not file_name and not sheet_name:
        return []

    p = resolve_path(db_path)
    if not p.exists():
        return []

    conn = sqlite3.connect(p)
    cursor = conn.cursor()
    try:
        requested_years = set(YEAR_TOKEN_RE.findall(str(file_name or "")))

        # Granularity is part of the source identity.  Treating a monthly
        # table as a quarterly table produces plausible-looking but invalid
        # calculations, so explicit requests must never cross this boundary.
        requested_text = f"{file_name or ''} {sheet_name or ''}"
        if re.search(r"(?:季度|季报|季末|年-季度)", requested_text):
            requested_granularity = "quarter"
        elif re.search(
            r"(?:(?:19|20)\d{2}年)?(?:0?[1-9]|1[0-2])月|(?:月度|月份|月报|月末)",
            requested_text,
        ):
            requested_granularity = "month"
        else:
            requested_granularity = None

        def matches_granularity(title: str | None) -> bool:
            if not requested_granularity or not title:
                return True
            text = str(title)
            has_quarter = bool(re.search(r"(?:季度|季报|季末|年-季度)", text))
            has_month = bool(
                re.search(
                    r"(?:(?:19|20)\d{2}年)?(?:0?[1-9]|1[0-2])月|(?:月度|月份|月报|月末)",
                    text,
                )
            )
            if requested_granularity == "quarter":
                return has_quarter and not has_month
            return has_month and not has_quarter

        def filter_granularity(titles: list[str]) -> list[str]:
            return [title for title in titles if matches_granularity(title)]

        def query_titles(pattern: str) -> list[str]:
            """Return titles matching a name while respecting an explicit year."""
            if not pattern:
                return []
            like = f"%{pattern}%"
            if not requested_years:
                cursor.execute(
                    "SELECT DISTINCT title FROM chunks "
                    "WHERE chunk_type='table' AND (title LIKE ? OR table_name LIKE ?)",
                    (like, like),
                )
                return filter_granularity([r[0] for r in cursor.fetchall()])

            # A source title can be normalized by module 1 (for example the year
            # is moved into table_name or the row text). Keep only candidates
            # carrying the requested year in one of those authoritative fields.
            year_clauses = []
            year_params: list[str] = []
            for year in sorted(requested_years):
                year_like = f"%{year}%"
                year_clauses.append(
                    "(title LIKE ? OR table_name LIKE ? OR metadata_json LIKE ?)"
                )
                year_params.extend([year_like, year_like, f'%\"period\": \"{year}\"%'])
            cursor.execute(
                "SELECT DISTINCT title FROM chunks WHERE chunk_type='table' "
                "AND (title LIKE ? OR table_name LIKE ?) AND ("
                + " OR ".join(year_clauses)
                + ")",
                [like, like, *year_params],
            )
            return filter_granularity([r[0] for r in cursor.fetchall()])

        candidates: list[str] = []

        # 1. Exact LIKE
        if file_name:
            candidates.extend(query_titles(file_name))

            # Titles in the source attachments are not consistent about
            # where the year and the quarter marker are placed. Compare
            # canonical forms after a broad family-name lookup.
            family = re.sub(r"(?:19|20)\d{2}年", "", file_name)
            family = re.sub(r"[（(].*?[）)]", "", family).strip()
            cursor.execute(
                "SELECT DISTINCT title FROM chunks WHERE chunk_type='table' AND title LIKE ?",
                (f"%{family}%",),
            )
            candidates = filter_granularity([r[0] for r in cursor.fetchall()])
            wanted = _canonical_title(file_name)
            matches = [t for t in candidates if _canonical_title(t) == wanted]
            if matches:
                return matches

        # 2. Synonyms & Quarter normalizations
        if file_name:
            variants = [
                file_name.replace("财产保险公司", "财产险公司"),
                file_name.replace("财产险公司", "财产保险公司"),
                file_name.replace("人身保险公司", "人身险公司"),
                file_name.replace("人身险公司", "人身保险公司"),
                file_name.replace("4季度", "四季度")
                .replace("3季度", "三季度")
                .replace("2季度", "二季度")
                .replace("1季度", "一季度"),
                file_name.replace("四季度", "4季度")
                .replace("三季度", "3季度")
                .replace("二季度", "2季度")
                .replace("一季度", "1季度"),
                file_name.replace("（季度）", "(季度)").replace("(季度)", "（季度）"),
                file_name.replace("情况表", "情况"),
                file_name.replace("情况", "情况表"),
            ]
            month_match = re.search(
                r"((?:19|20)\d{2})年(0?[1-9]|1[0-2])月", file_name
            )
            if month_match:
                year, month = month_match.groups()
                month_span = month_match.span()
                variants.extend(
                    [
                        file_name[: month_span[0]]
                        + f"{year}年{int(month)}月"
                        + file_name[month_span[1] :],
                        file_name[: month_span[0]]
                        + f"{year}年{int(month):02d}月"
                        + file_name[month_span[1] :],
                    ]
                )
            m_year = re.search(r"^(?:19|20)\d{2}年?", file_name)
            if m_year:
                no_year = file_name[len(m_year.group(0)) :].strip()
                variants.append(no_year)
                variants.append(no_year.replace("情况", "情况表"))
                variants.append(no_year.replace("情况表", "情况"))

            for v in variants:
                if v != file_name:
                    candidates.extend(query_titles(v))

            # An attachment label and its internal table title can be entirely
            # different (for example, "银行业总资产、总负债" contains the table
            # "银行业金融机构资产负债情况表"). Resolve the attachment through the
            # parsed-document manifest, then take table titles from that exact
            # document instead of relying on lexical overlap between titles.
            document_ids = _find_document_ids(p, file_name)
            if document_ids:
                placeholders = ",".join("?" for _ in document_ids)
                cursor.execute(
                    f"SELECT DISTINCT title FROM chunks WHERE chunk_type='table' "
                    f"AND doc_id IN ({placeholders})",
                    document_ids,
                )
                candidates.extend(
                    filter_granularity([r[0] for r in cursor.fetchall()])
                )

        # 3. Sheet name fallback
        if sheet_name:
            clean_sheet = (
                sheet_name.replace("（月度）", "")
                .replace("(月度)", "")
                .replace("（季度）", "")
                .replace("(季度)", "")
                .strip()
            )
            if clean_sheet:
                cursor.execute(
                    "SELECT DISTINCT title FROM chunks WHERE chunk_type='table' AND sheet_name LIKE ?",
                    (f"%{clean_sheet}%",),
                )
                candidates.extend(filter_granularity([r[0] for r in cursor.fetchall()]))

        # Preserve insertion order, then prefer titles carrying the explicit
        # source year. A no-year generic title is only acceptable when no year
        # was present in the request.
        unique = list(dict.fromkeys(candidates))
        if requested_years:
            year_filtered = []
            for title in unique:
                cursor.execute(
                    "SELECT 1 FROM chunks WHERE chunk_type='table' AND title = ? "
                    f"AND (" + " OR ".join(
                        "title LIKE ? OR table_name LIKE ? OR metadata_json LIKE ?"
                        for _ in requested_years
                    ) + ") LIMIT 1",
                    [title, *sum(([
                        f"%{y}%", f"%{y}%", f'%\"period\": \"{y}\"%'
                    ] for y in sorted(requested_years)), [])],
                )
                if cursor.fetchone():
                    year_filtered.append(title)
            unique = year_filtered
        return unique
    finally:
        conn.close()


class MultiTargetRetriever:
    """Discrete Multi-Target Retrieval Engine for RegTrust-RAG."""

    def __init__(
        self,
        reader: KnowledgeBaseReader | None = None,
        *,
        db_path: str | Path = "data/processed/kb_rebuild/metadata.db",
        index_dir: str | Path = "indexes/kb_rebuild",
    ) -> None:
        self.db_path = resolve_path(db_path)
        self.reader = reader or KnowledgeBaseReader(self.db_path, vector_index_dir=index_dir)

    def build_tasks(self, question: str, task_plan: TaskPlan) -> list[TargetRetrievalTask]:
        """Convert a TaskPlan into a list of discrete TargetRetrievalTasks."""
        task_type = task_plan.task_type
        tasks: list[TargetRetrievalTask] = []

        if task_type == "TABLE_COMPARE":
            file_name = task_plan.source.file_name if task_plan.source else None
            sheet_name = task_plan.source.sheet_name if task_plan.source else None
            scope = task_plan.scope

            for cand in task_plan.candidates:
                task_id = f"CAND_{cand.label}"
                target_text = f"{scope or ''} {cand.target}".strip()
                tasks.append(
                    TargetRetrievalTask(
                        task_id=task_id,
                        target=target_text,
                        task_type="TABLE_COMPARE",
                        source_constraints={
                            "file_name": file_name,
                            "sheet_name": sheet_name,
                            "scope": scope,
                        },
                        extra={
                            "label": cand.label,
                            "candidate_target": cand.target,
                            "scope": scope,
                        },
                    )
                )

        elif task_type == "TABLE_CALCULATION":
            file_name = task_plan.source.file_name if task_plan.source else None
            sheet_name = task_plan.source.sheet_name if task_plan.source else None

            for idx, op in enumerate(task_plan.operands, 1):
                task_id = f"OPERAND_{idx}"
                target_text = f"{op.row or ''} {op.column or op.name}".strip()
                tasks.append(
                    TargetRetrievalTask(
                        task_id=task_id,
                        target=target_text,
                        task_type="TABLE_CALCULATION",
                        source_constraints={
                            "file_name": file_name,
                            "sheet_name": sheet_name,
                            "row": op.row,
                            "column": op.column,
                        },
                        extra={
                            "operand_name": op.name,
                            "row": op.row,
                            "column": op.column,
                        },
                    )
                )

        elif task_type in {"FACT_SINGLE_CHOICE", "FACT_MULTI_CHOICE"}:
            doc_name = (
                task_plan.source_constraints.document_name
                if task_plan.source_constraints
                else None
            )
            article_no = (
                task_plan.source_constraints.article_number
                if task_plan.source_constraints
                else None
            )

            if isinstance(task_plan.options, list):
                for opt in task_plan.options:
                    task_id = f"OPT_{opt.label}"
                    sub_targets = getattr(opt, "sub_claims", []) or []
                    tasks.append(
                        TargetRetrievalTask(
                            task_id=task_id,
                            target=opt.claim,
                            task_type=task_type,
                            source_constraints={
                                "document_name": doc_name,
                                "article_number": article_no,
                            },
                            sub_targets=sub_targets,
                            extra={
                                "label": opt.label,
                                "claim": opt.claim,
                                "sub_claims": sub_targets,
                            },
                        )
                    )

        elif task_type == "TABLE_LOOKUP":
            file_name = task_plan.source.file_name if task_plan.source else None
            sheet_name = task_plan.source.sheet_name if task_plan.source else None
            scope = task_plan.scope

            for idx, target_item in enumerate(task_plan.targets, 1):
                task_id = f"TARGET_{idx}"
                target_text = f"{target_item.indicator or ''} {target_item.column or ''} {target_item.row or ''}".strip()
                tasks.append(
                    TargetRetrievalTask(
                        task_id=task_id,
                        target=target_text,
                        task_type="TABLE_LOOKUP",
                        source_constraints={
                            "file_name": file_name,
                            "sheet_name": sheet_name,
                            "scope": scope,
                            "row": target_item.row,
                            "column": target_item.column,
                        },
                        extra={
                            "indicator": target_item.indicator,
                            "row": target_item.row,
                            "column": target_item.column,
                        },
                    )
                )

        else:  # DIRECT_FACT_QA
            constraints = (
                task_plan.source_constraints.to_dict()
                if task_plan.source_constraints
                else {}
            )
            tasks.append(
                TargetRetrievalTask(
                    task_id="T1",
                    target=question,
                    task_type="DIRECT_FACT_QA",
                    source_constraints=constraints,
                )
            )

        return tasks

    def retrieve(
        self,
        question: str,
        task_plan: TaskPlan,
        top_k: int = 5,
    ) -> MultiTargetRetrievalResponse:
        """Execute discrete retrieval for all tasks in task_plan and aggregate results."""
        tasks = self.build_tasks(question, task_plan)
        results: list[TargetRetrievalResult] = []

        logger.info(
            f"[MultiTargetRetriever] 启动多目标检索 | task_type={task_plan.task_type} | 任务总数={len(tasks)}"
        )

        per_task_k = self._per_task_top_k(task_plan.task_type, tasks, top_k)
        for task in tasks:
            if task.task_type in {"TABLE_COMPARE", "TABLE_CALCULATION", "TABLE_LOOKUP"}:
                res = self._execute_table_task(task, top_k=per_task_k)
            elif task.task_type in {"FACT_SINGLE_CHOICE", "FACT_MULTI_CHOICE"}:
                res = self._execute_fact_choice_task(task, top_k=per_task_k)
            else:
                res = self._execute_direct_fact_task(task, top_k=top_k)
            results.append(res)

        evidence_budget = self._evidence_budget(task_plan.task_type, results, top_k)
        merged_evidence = self._merge_results(results, budget=evidence_budget)
        successful_task_ids = [r.task_id for r in results if r.status == "SUCCESS" and r.evidence]
        requires_full_target_coverage = task_plan.task_type in {
            "TABLE_COMPARE",
            "TABLE_CALCULATION",
        }
        overall_status = "no_evidence" if not merged_evidence else "answerable"
        if (
            overall_status == "answerable"
            and requires_full_target_coverage
            and len(successful_task_ids) < len(tasks)
        ):
            overall_status = "degraded"

        response = MultiTargetRetrievalResponse(
            query=question,
            task_type=task_plan.task_type,
            task_plan=task_plan,
            retrieval_tasks=tasks,
            retrieval_results=results,
            merged_evidence=merged_evidence,
            overall_status=overall_status,
            diagnostics={
                "task_count": len(tasks),
                "success_count": sum(1 for r in results if r.status == "SUCCESS"),
                "merged_evidence_count": len(merged_evidence),
                "requested_top_k": top_k,
                "per_task_top_k": per_task_k,
                "evidence_budget": evidence_budget,
                "covered_task_ids": successful_task_ids,
                "missing_task_ids": [
                    task.task_id for task in tasks if task.task_id not in successful_task_ids
                ],
                "requires_full_target_coverage": requires_full_target_coverage,
            },
        )
        return response

    @staticmethod
    def _per_task_top_k(
        task_type: str,
        tasks: Sequence[TargetRetrievalTask],
        requested_top_k: int,
    ) -> int:
        if task_type == "TABLE_LOOKUP" or len(tasks) <= 1:
            return max(requested_top_k, 3)
        if task_type == "FACT_MULTI_CHOICE":
            max_sub_targets = max((len(task.sub_targets) for task in tasks), default=1)
            return max(FACT_CHOICE_EVIDENCE_PER_TASK, max_sub_targets)
        if task_type == "FACT_SINGLE_CHOICE":
            return FACT_CHOICE_EVIDENCE_PER_TASK
        return MULTI_TARGET_EVIDENCE_PER_TASK

    @staticmethod
    def _evidence_budget(
        task_type: str,
        results: Sequence[TargetRetrievalResult],
        requested_top_k: int,
    ) -> int:
        successful_count = sum(1 for result in results if result.status == "SUCCESS" and result.evidence)
        if task_type in {
            "TABLE_COMPARE",
            "TABLE_CALCULATION",
            "FACT_SINGLE_CHOICE",
            "FACT_MULTI_CHOICE",
        }:
            return max(requested_top_k, successful_count * MULTI_TARGET_EVIDENCE_PER_TASK)
        return max(requested_top_k, successful_count)

    def _execute_table_task(
        self, task: TargetRetrievalTask, top_k: int = 3
    ) -> TargetRetrievalResult:
        """Execute targeted table retrieval matching cells, rows, and candidate indicators."""
        file_name = task.source_constraints.get("file_name")
        sheet_name = task.source_constraints.get("sheet_name")
        target = task.target
        cand_target = task.extra.get("candidate_target") or ""
        row_target = task.extra.get("row") or ""
        col_target = task.extra.get("column") or ""

        evidence: list[SearchResult] = []

        # 1. High-precision SQL Direct Match via Title / Sheet / Row / Metric
        if self.db_path.exists():
            matched_titles = find_matching_table_titles(
                self.db_path, file_name, sheet_name
            )
            if not matched_titles and sheet_name:
                # Fallback for year/parenthesis ordering variants in Excel
                # attachment titles (the sheet name is stable).
                clean_sheet = re.sub(r"[（(](?:季度|月度)[）)]", "", sheet_name).strip()
                rows = sqlite3.connect(self.db_path).execute(
                    "SELECT DISTINCT title FROM chunks WHERE chunk_type='table' AND sheet_name LIKE ?",
                    (f"%{clean_sheet}%",),
                ).fetchall()
                year = re.search(r"(?:19|20)\d{2}", file_name or "")
                year_text = year.group(0) if year else ""
                matched_titles = [
                    r[0] for r in rows
                    if not year_text or year_text in str(r[0]) or year_text in str(r[0]).replace("年", "")
                ] or [r[0] for r in rows]
            conn = sqlite3.connect(self.db_path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            try:
                for title in matched_titles:
                    where_clauses = ["chunk_type='table'", "title = ?"]
                    params: list[Any] = [title]

                    if sheet_name:
                        clean_sheet = sheet_name.replace("（月度）", "").replace("(月度)", "").replace("（季度）", "").replace("(季度)", "").strip()
                        where_clauses.append("sheet_name LIKE ?")
                        params.append(f"%{clean_sheet}%")

                    month_match = re.search(
                        r"((?:19|20)\d{2})年(0?[1-9]|1[0-2])月",
                        file_name or "",
                    )
                    quarter_match = re.search(
                        r"((?:19|20)\d{2})年(?:第)?([1-4一二三四])季度",
                        file_name or "",
                    )
                    if month_match:
                        year, month = month_match.groups()
                        month_number = int(month)
                        period = f"{year}-{month_number:02d}"
                        where_clauses.append(
                            "(metadata_json LIKE ? OR text LIKE ? OR text LIKE ? "
                            "OR title LIKE ? OR title LIKE ?)"
                        )
                        params.extend(
                            [
                                f'%"period": "{period}%',
                                f"%{year}年{month_number}月%",
                                f"%{year}年{month_number:02d}月%",
                                f"%{year}年{month_number}月%",
                                f"%{year}年{month_number:02d}月%",
                            ]
                        )
                    elif quarter_match:
                        year, quarter = quarter_match.groups()
                        quarter_num = {
                            "一": "1", "二": "2", "三": "3", "四": "4",
                        }.get(quarter, quarter)
                        quarter_cn = {
                            "1": "一", "2": "二", "3": "三", "4": "四",
                        }[quarter_num]
                        where_clauses.append(
                            "(metadata_json LIKE ? OR text LIKE ? OR text LIKE ? OR title LIKE ? OR title LIKE ?)"
                        )
                        params.extend(
                            [
                                f'%"period": "{year}-Q{quarter_num}%',
                                f"%{year}年{quarter_num}季度%",
                                f"%{year}年{quarter_cn}季度%",
                                f"%{year}年{quarter_num}季度%",
                                f"%{year}年{quarter_cn}季度%",
                            ]
                        )

                    # Match specific candidate or operand row
                    match_term = cand_target or row_target
                    if match_term:
                        match_aliases = table_metric_aliases(match_term)
                        # Excel row labels are sometimes exported with visual
                        # spaces (``天 津``/``北 京``), while users normally
                        # type the compact form (``天津``/``北京``). Match
                        # both representations at the SQL layer so every
                        # regional/机构名称 benefits without per-name rules.
                        clauses = []
                        for _ in match_aliases:
                            clauses.append(
                                "text LIKE ? OR metadata_json LIKE ? OR "
                                "REPLACE(REPLACE(text, ' ', ''), '　', '') LIKE ? OR "
                                "REPLACE(REPLACE(metadata_json, ' ', ''), '　', '') LIKE ?"
                            )
                        where_clauses.append("(" + " OR ".join(clauses) + ")")
                        for alias in match_aliases:
                            compact_alias = re.sub(r"[\s\u3000]+", "", alias)
                            params.extend(
                                (
                                    f"%{alias}%",
                                    f"%{alias}%",
                                    f"%{compact_alias}%",
                                    f"%{compact_alias}%",
                                )
                            )

                    # "总资产" appears in several institution sections of the
                    # quarterly balance-sheet table. When the source explicitly
                    # names the banking total, bind it to the first overall
                    # section instead of returning a different institution's
                    # same-named row.
                    if file_name and "银行业总资产" in file_name and row_target == "总资产":
                        where_clauses.append("text LIKE ?")
                        params.append("%1. 银行业金融机构=总资产%")

                    sql = f"SELECT * FROM chunks WHERE {' AND '.join(where_clauses)} LIMIT ?"
                    params.append(top_k * 2)
                    rows = cursor.execute(sql, tuple(params)).fetchall()

                    if file_name and "银行业总资产" in file_name and row_target == "总资产" and rows:
                        # The workbook repeats the same metric for each
                        # institution section. The unqualified file-level
                        # "总资产" means the first overall section; keep its
                        # row and all of its quarter cells only.
                        row_indices = []
                        for row in rows:
                            try:
                                metadata = json.loads(row["metadata_json"] or "{}")
                                row_indices.append(int(metadata.get("row_index")))
                            except (TypeError, ValueError):
                                continue
                        if row_indices:
                            first_row = min(row_indices)
                            rows = [
                                row for row in rows
                                if json.loads(row["metadata_json"] or "{}").get("row_index") == first_row
                            ]

                    for r in rows:
                        meta = json.loads(r["metadata_json"]) if r["metadata_json"] else {}
                        meta["matched_target_task"] = task.task_id
                        source_info = SourceInfo(
                            doc_id=r["doc_id"] or "",
                            title=r["title"] or "",
                            issuer=r["issuer"] or "",
                            publish_date=r["publish_date"] or "",
                            section_path=r["section_path"] or "",
                            clause_no=r["clause_no"] or "",
                            sheet_name=r["sheet_name"] or "",
                            table_name=r["table_name"] or "",
                        )
                        sr = SearchResult(
                            chunk_id=r["chunk_id"],
                            chunk_type=r["chunk_type"],
                            score=100.0,
                            text=r["text"],
                            source=source_info,
                            metadata=meta,
                        )
                        sr = _narrow_table_dimension(sr, col_target)
                        if not any(e.chunk_id == sr.chunk_id for e in evidence):
                            evidence.append(sr)
            finally:
                conn.close()

        # 2. Hybrid Reader Search Fallback/Enrichment
        # SQL direct matching is authoritative for a constrained table target.
        # Enriching an already successful match with vector neighbours can add
        # other rows/columns from the same table and make the evidence package
        # ambiguous. Fall back only when the precise path found nothing.
        if not evidence:
            lookup_aliases = table_metric_aliases(cand_target or row_target)
            lookup_target = lookup_aliases[-1] if lookup_aliases else target
            query_str = f"{file_name or ''} {task.source_constraints.get('scope') or ''} {lookup_target}".strip()
            filters = {"title": file_name} if file_name else {}
            reader_results = self.reader.search(
                query_str,
                top_k=top_k,
                chunk_type="table",
                filters=filters,
                rerank=True,
            )
            for sr in reader_results:
                sr = _narrow_table_dimension(sr, col_target)
                if not any(e.chunk_id == sr.chunk_id for e in evidence):
                    sr.metadata["matched_target_task"] = task.task_id
                    evidence.append(sr)

        status = "SUCCESS" if evidence else "NO_EVIDENCE"
        return TargetRetrievalResult(
            task_id=task.task_id,
            target=task.target,
            status=status,
            evidence=evidence[:top_k],
            diagnostics={"candidate_count": len(evidence)},
        )

    def _execute_fact_choice_task(
        self, task: TargetRetrievalTask, top_k: int = 3
    ) -> TargetRetrievalResult:
        """Execute discrete fact retrieval for a single choice option claim/sub-claims."""
        doc_name = _normalize_document_name(task.source_constraints.get("document_name"))
        filters = {"title": doc_name} if doc_name else {}
        doc_ids = _preferred_document_ids(self.db_path, doc_name)
        if doc_ids:
            filters = {"doc_id": doc_ids[0]}

        evidence: list[SearchResult] = []

        # If option contains multiple sub-claims (FACT_MULTI_CHOICE paired claims)
        if task.sub_targets and len(task.sub_targets) > 1:
            for sub_claim in task.sub_targets:
                sc_res = self.reader.search(
                    sub_claim,
                    top_k=2,
                    filters=filters,
                    rerank=True,
                )
                # For factual options, also query structured table chunks;
                # compact rows often contain the decisive value even when
                # clause-text search returns only surrounding prose.
                table_res = self.reader.search(
                    sub_claim,
                    top_k=3,
                    chunk_type="table",
                    filters=filters,
                    rerank=True,
                )
                if table_res:
                    seen = {x.chunk_id for x in table_res}
                    # Put structured rows first so the per-subclaim evidence
                    # budget does not discard the decisive table value.
                    sc_res = list(table_res) + [x for x in sc_res if x.chunk_id not in seen]
                for sr in sc_res[:4]:
                    if not any(e.chunk_id == sr.chunk_id for e in evidence):
                        sr.metadata["matched_target_task"] = task.task_id
                        sr.metadata["matched_sub_claim"] = sub_claim
                        evidence.append(sr)
        else:
            claim_res = self.reader.search(
                task.target,
                top_k=top_k,
                filters=filters,
                rerank=True,
            )
            claim_res = self._expand_clause_neighbors(claim_res, task.task_id)
            for sr in claim_res:
                sr.metadata["matched_target_task"] = task.task_id
                evidence.append(sr)

        status = "SUCCESS" if evidence else "NO_EVIDENCE"
        return TargetRetrievalResult(
            task_id=task.task_id,
            target=task.target,
            status=status,
            evidence=evidence,
            diagnostics={
                "candidate_count": len(evidence),
                "document_name": doc_name,
                "resolved_doc_ids": doc_ids,
                "source_filter": filters,
            },
        )

    def _expand_clause_neighbors(
        self,
        results: Sequence[SearchResult],
        task_id: str,
        *,
        radius: int = 2,
    ) -> list[SearchResult]:
        """Add contiguous clause chunks from the same document and section family."""
        if not results or not self.db_path.exists():
            return list(results)

        expanded: list[SearchResult] = []
        seen: set[str] = set()
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            for seed in results:
                if seed.chunk_type != "clause":
                    if seed.chunk_id not in seen:
                        expanded.append(seed)
                        seen.add(seed.chunk_id)
                    continue

                match = re.match(r"^(.*?)(\d+)$", seed.chunk_id)
                if not match or not seed.source.doc_id:
                    if seed.chunk_id not in seen:
                        expanded.append(seed)
                        seen.add(seed.chunk_id)
                    continue

                prefix, number_text = match.groups()
                number = int(number_text)
                lower = max(0, number - radius)
                upper = number + radius
                rows = conn.execute(
                    "SELECT * FROM chunks WHERE doc_id = ? AND chunk_type = 'clause' "
                    "AND chunk_id LIKE ?",
                    (seed.source.doc_id, f"{prefix}%"),
                ).fetchall()
                section_root = str(seed.source.section_path[0]) if seed.source.section_path else ""
                neighbours: list[tuple[int, SearchResult]] = []
                for row in rows:
                    row_match = re.match(rf"^{re.escape(prefix)}(\d+)$", str(row["chunk_id"]))
                    if not row_match:
                        continue
                    row_number = int(row_match.group(1))
                    if row_number < lower or row_number > upper:
                        continue
                    candidate = _row_to_search_result(row, score=seed.score)
                    candidate_root = (
                        str(candidate.source.section_path[0])
                        if candidate.source.section_path
                        else ""
                    )
                    if section_root and candidate_root and candidate_root != section_root:
                        continue
                    candidate.metadata["matched_target_task"] = task_id
                    if candidate.chunk_id != seed.chunk_id:
                        candidate.metadata["retrieval_expansion"] = "contiguous_clause_neighbor"
                        candidate.metadata["neighbor_of"] = seed.chunk_id
                    neighbours.append((row_number, candidate))

                for _, candidate in sorted(neighbours, key=lambda item: item[0]):
                    if candidate.chunk_id not in seen:
                        expanded.append(candidate)
                        seen.add(candidate.chunk_id)

            for seed in results:
                if seed.chunk_id not in seen:
                    expanded.append(seed)
                    seen.add(seed.chunk_id)
        finally:
            conn.close()
        return expanded

    def _execute_direct_fact_task(
        self, task: TargetRetrievalTask, top_k: int = 5
    ) -> TargetRetrievalResult:
        """Execute standard direct fact retrieval."""
        doc_name = _normalize_document_name(task.source_constraints.get("document_name"))
        filters = {"title": doc_name} if doc_name else {}
        doc_ids = _preferred_document_ids(self.db_path, doc_name)
        evidence = self.reader.search(
            task.target,
            top_k=top_k,
            filters=filters,
            rerank=True,
        )
        if not evidence and doc_ids:
            evidence = self.reader.search(
                task.target,
                top_k=top_k,
                filters={"doc_id": doc_ids[0]},
                rerank=True,
            )
        for sr in evidence:
            sr.metadata["matched_target_task"] = task.task_id
        status = "SUCCESS" if evidence else "NO_EVIDENCE"
        return TargetRetrievalResult(
            task_id=task.task_id,
            target=task.target,
            status=status,
            evidence=evidence,
            diagnostics={"candidate_count": len(evidence)},
        )

    def _merge_results(
        self,
        results: Sequence[TargetRetrievalResult],
        *,
        budget: int | None = None,
    ) -> list[SearchResult]:
        """Merge evidence round-robin so every successful target is represented first."""
        merged: list[SearchResult] = []
        seen: dict[str, SearchResult] = {}
        max_depth = max((len(result.evidence) for result in results), default=0)
        limit = budget if budget is not None and budget > 0 else None

        for rank in range(max_depth):
            for result in results:
                if rank >= len(result.evidence):
                    continue
                item = result.evidence[rank]
                existing = seen.get(item.chunk_id)
                if existing is not None:
                    matched = existing.metadata.setdefault("matched_target_tasks", [])
                    for task_id in (existing.metadata.get("matched_target_task"), result.task_id):
                        if task_id and task_id not in matched:
                            matched.append(task_id)
                    continue
                item.metadata["matched_target_task"] = result.task_id
                item.metadata["matched_target_tasks"] = [result.task_id]
                seen[item.chunk_id] = item
                merged.append(item)
                if limit is not None and len(merged) >= limit:
                    return merged
        return merged


def _narrow_table_dimension(candidate: SearchResult, requested_dimension: str) -> SearchResult:
    """Select one requested table column when metadata exposes a dimension map.

    Module 1 keeps the row label and all data cells in ``metadata.values``.
    Returning the complete row for a request such as ``大型商业银行`` lets a
    downstream generator accidentally use a neighbouring institution/period.
    This helper narrows only on an explicit, exact dimension; broad labels such
    as ``年-季度`` intentionally remain untouched because they represent more
    than one quarter and must not be guessed.
    """
    if candidate.chunk_type != "table" or not requested_dimension:
        return candidate
    dimension = _normalize_dimension(requested_dimension)
    if not dimension or dimension in {"年季度", "季度", "月度", "本年累计", "截至当期"}:
        return candidate
    values = [item for item in (candidate.metadata.get("values") or []) if isinstance(item, dict)]
    matches = []
    for item in values:
        header = _normalize_dimension(item.get("header") or item.get("col_header"))
        if header == dimension:
            matches.append(item)
    if len(matches) != 1:
        return candidate

    selected = matches[0]
    metadata = dict(candidate.metadata)
    cell_ref = str(selected.get("cell_ref") or candidate.source.cell_ref)
    metadata["values"] = [dict(selected)]
    metadata["cell_ref"] = cell_ref
    metadata["value"] = str(selected.get("value") or "")
    if selected.get("value_numeric") is not None:
        metadata["value_numeric"] = str(selected["value_numeric"])
    metadata["col_header"] = str(selected.get("header") or selected.get("col_header") or "")
    metadata["table_cell_selection"] = {
        "status": "exact_dimension_cell",
        "requested_dimension": requested_dimension,
        "original_cell_ref": candidate.source.cell_ref,
        "selected_cell_ref": str(selected.get("cell_ref") or candidate.source.cell_ref),
        "selected_value_count": 1,
        "value_preserved_as_source": True,
    }
    # Keep the original row text for backwards-compatible diagnostics while
    # exposing the authoritative single-cell value through metadata/source.
    text = candidate.text
    return SearchResult(
        chunk_id=candidate.chunk_id,
        chunk_type=candidate.chunk_type,
        score=candidate.score,
        text=text,
        source=replace(candidate.source, cell_ref=cell_ref),
        metadata=metadata,
    )


def _normalize_dimension(value: object) -> str:
    return re.sub(r"[\s\u3000_/\\-]+", "", str(value or "").strip().lower())

multi_target_retriever = MultiTargetRetriever()

__all__ = [
    "MultiTargetRetriever",
    "multi_target_retriever",
    "find_matching_table_titles",
]
