"""Multi-target Retrieval Engine for RegTrust-RAG.

Executes targeted, discrete retrieval for each task generated by Task Planner:
  - TABLE_COMPARE: Discretely searches for every candidate indicator
  - TABLE_CALCULATION: Discretely extracts every mathematical operand
  - FACT_SINGLE_CHOICE / FACT_MULTI_CHOICE: Discretely retrieves evidence for each option claim and sub-claim
  - TABLE_LOOKUP: Targeted table coordinate retrieval
  - DIRECT_FACT_QA: Targeted regulatory fact retrieval

Adheres strictly to the user requirement:
  - Input: {"retrieval_tasks": [{"task_id": "T1", "target": "", "source_constraints": {}}]}
  - Output: {"retrieval_results": [{"task_id": "T1", "status": "SUCCESS", "evidence": []}]}
  - Avoids naive TopK inflation; executes deterministic multi-target retrieval.
"""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path
from typing import Any, Sequence

from app.indexing.index_reader import KnowledgeBaseReader
from app.schemas.chunk_schema import SearchResult, SourceInfo
from app.schemas.multi_target_retrieval_schema import (
    MultiTargetRetrievalResponse,
    TargetRetrievalResult,
    TargetRetrievalTask,
)
from app.schemas.task_plan_schema import TaskPlan
from app.utils.logger import get_logger
from app.utils.paths import resolve_path

logger = get_logger("app.retrieval.multi_target")


def find_matching_table_titles(
    db_path: Path | str,
    file_name: str | None,
    sheet_name: str | None = None,
) -> list[str]:
    """Find actual matching table titles in metadata.db supporting quarter synonyms and naming variants."""
    if not file_name and not sheet_name:
        return []

    p = resolve_path(db_path)
    if not p.exists():
        return []

    conn = sqlite3.connect(p)
    cursor = conn.cursor()
    try:
        # 1. Exact LIKE
        if file_name:
            cursor.execute(
                "SELECT DISTINCT title FROM chunks WHERE chunk_type='table' AND title LIKE ?",
                (f"%{file_name}%",),
            )
            rows = cursor.fetchall()
            if rows:
                return [r[0] for r in rows]

        # 2. Synonyms & Quarter normalizations
        if file_name:
            variants = [
                file_name.replace("财产保险公司", "财产险公司"),
                file_name.replace("财产险公司", "财产保险公司"),
                file_name.replace("人身保险公司", "人身险公司"),
                file_name.replace("人身险公司", "人身保险公司"),
                file_name.replace("4季度", "四季度")
                .replace("3季度", "三季度")
                .replace("2季度", "二季度")
                .replace("1季度", "一季度"),
                file_name.replace("四季度", "4季度")
                .replace("三季度", "3季度")
                .replace("二季度", "2季度")
                .replace("一季度", "1季度"),
                file_name.replace("（季度）", "(季度)").replace("(季度)", "（季度）"),
                file_name.replace("情况表", "情况"),
                file_name.replace("情况", "情况表"),
            ]
            m_year = re.search(r"^(?:19|20)\d{2}年?", file_name)
            if m_year:
                no_year = file_name[len(m_year.group(0)) :].strip()
                variants.append(no_year)
                variants.append(no_year.replace("情况", "情况表"))
                variants.append(no_year.replace("情况表", "情况"))

            for v in variants:
                if v != file_name:
                    cursor.execute(
                        "SELECT DISTINCT title FROM chunks WHERE chunk_type='table' AND title LIKE ?",
                        (f"%{v}%",),
                    )
                    rows = cursor.fetchall()
                    if rows:
                        return [r[0] for r in rows]

        # 3. Sheet name fallback
        if sheet_name:
            clean_sheet = (
                sheet_name.replace("（月度）", "")
                .replace("(月度)", "")
                .replace("（季度）", "")
                .replace("(季度)", "")
                .strip()
            )
            cursor.execute(
                "SELECT DISTINCT title FROM chunks WHERE chunk_type='table' AND sheet_name LIKE ?",
                (f"%{clean_sheet}%",),
            )
            rows = cursor.fetchall()
            if rows:
                return [r[0] for r in rows]

        return []
    finally:
        conn.close()


class MultiTargetRetriever:
    """Discrete Multi-Target Retrieval Engine for RegTrust-RAG."""

    def __init__(
        self,
        reader: KnowledgeBaseReader | None = None,
        *,
        db_path: str | Path = "data/processed/kb_rebuild/metadata.db",
        index_dir: str | Path = "indexes/kb_rebuild",
    ) -> None:
        self.db_path = resolve_path(db_path)
        self.reader = reader or KnowledgeBaseReader(self.db_path, vector_index_dir=index_dir)

    def build_tasks(self, question: str, task_plan: TaskPlan) -> list[TargetRetrievalTask]:
        """Convert a TaskPlan into a list of discrete TargetRetrievalTasks."""
        task_type = task_plan.task_type
        tasks: list[TargetRetrievalTask] = []

        if task_type == "TABLE_COMPARE":
            file_name = task_plan.source.file_name if task_plan.source else None
            sheet_name = task_plan.source.sheet_name if task_plan.source else None
            scope = task_plan.scope

            for cand in task_plan.candidates:
                task_id = f"CAND_{cand.label}"
                target_text = f"{scope or ''} {cand.target}".strip()
                tasks.append(
                    TargetRetrievalTask(
                        task_id=task_id,
                        target=target_text,
                        task_type="TABLE_COMPARE",
                        source_constraints={
                            "file_name": file_name,
                            "sheet_name": sheet_name,
                            "scope": scope,
                        },
                        extra={
                            "label": cand.label,
                            "candidate_target": cand.target,
                            "scope": scope,
                        },
                    )
                )

        elif task_type == "TABLE_CALCULATION":
            file_name = task_plan.source.file_name if task_plan.source else None
            sheet_name = task_plan.source.sheet_name if task_plan.source else None

            for idx, op in enumerate(task_plan.operands, 1):
                task_id = f"OPERAND_{idx}"
                target_text = f"{op.row or ''} {op.column or op.name}".strip()
                tasks.append(
                    TargetRetrievalTask(
                        task_id=task_id,
                        target=target_text,
                        task_type="TABLE_CALCULATION",
                        source_constraints={
                            "file_name": file_name,
                            "sheet_name": sheet_name,
                            "row": op.row,
                            "column": op.column,
                        },
                        extra={
                            "operand_name": op.name,
                            "row": op.row,
                            "column": op.column,
                        },
                    )
                )

        elif task_type in {"FACT_SINGLE_CHOICE", "FACT_MULTI_CHOICE"}:
            doc_name = (
                task_plan.source_constraints.document_name
                if task_plan.source_constraints
                else None
            )
            article_no = (
                task_plan.source_constraints.article_number
                if task_plan.source_constraints
                else None
            )

            if isinstance(task_plan.options, list):
                for opt in task_plan.options:
                    task_id = f"OPT_{opt.label}"
                    sub_targets = getattr(opt, "sub_claims", []) or []
                    tasks.append(
                        TargetRetrievalTask(
                            task_id=task_id,
                            target=opt.claim,
                            task_type=task_type,
                            source_constraints={
                                "document_name": doc_name,
                                "article_number": article_no,
                            },
                            sub_targets=sub_targets,
                            extra={
                                "label": opt.label,
                                "claim": opt.claim,
                                "sub_claims": sub_targets,
                            },
                        )
                    )

        elif task_type == "TABLE_LOOKUP":
            file_name = task_plan.source.file_name if task_plan.source else None
            sheet_name = task_plan.source.sheet_name if task_plan.source else None
            scope = task_plan.scope

            for idx, target_item in enumerate(task_plan.targets, 1):
                task_id = f"TARGET_{idx}"
                target_text = f"{target_item.indicator or ''} {target_item.column or ''} {target_item.row or ''}".strip()
                tasks.append(
                    TargetRetrievalTask(
                        task_id=task_id,
                        target=target_text,
                        task_type="TABLE_LOOKUP",
                        source_constraints={
                            "file_name": file_name,
                            "sheet_name": sheet_name,
                            "scope": scope,
                            "row": target_item.row,
                            "column": target_item.column,
                        },
                        extra={
                            "indicator": target_item.indicator,
                            "row": target_item.row,
                            "column": target_item.column,
                        },
                    )
                )

        else:  # DIRECT_FACT_QA
            constraints = (
                task_plan.source_constraints.to_dict()
                if task_plan.source_constraints
                else {}
            )
            tasks.append(
                TargetRetrievalTask(
                    task_id="T1",
                    target=question,
                    task_type="DIRECT_FACT_QA",
                    source_constraints=constraints,
                )
            )

        return tasks

    def retrieve(
        self,
        question: str,
        task_plan: TaskPlan,
        top_k: int = 5,
    ) -> MultiTargetRetrievalResponse:
        """Execute discrete retrieval for all tasks in task_plan and aggregate results."""
        tasks = self.build_tasks(question, task_plan)
        results: list[TargetRetrievalResult] = []

        logger.info(
            f"[MultiTargetRetriever] 启动多目标检索 | task_type={task_plan.task_type} | 任务总数={len(tasks)}"
        )

        for task in tasks:
            if task.task_type in {"TABLE_COMPARE", "TABLE_CALCULATION", "TABLE_LOOKUP"}:
                res = self._execute_table_task(task, top_k=max(top_k, 3))
            elif task.task_type in {"FACT_SINGLE_CHOICE", "FACT_MULTI_CHOICE"}:
                res = self._execute_fact_choice_task(task, top_k=max(top_k, 3))
            else:
                res = self._execute_direct_fact_task(task, top_k=top_k)
            results.append(res)

        merged_evidence = self._merge_results(results)
        overall_status = "answerable" if merged_evidence else "no_evidence"

        response = MultiTargetRetrievalResponse(
            query=question,
            task_type=task_plan.task_type,
            task_plan=task_plan,
            retrieval_tasks=tasks,
            retrieval_results=results,
            merged_evidence=merged_evidence,
            overall_status=overall_status,
            diagnostics={
                "task_count": len(tasks),
                "success_count": sum(1 for r in results if r.status == "SUCCESS"),
                "merged_evidence_count": len(merged_evidence),
            },
        )
        return response

    def _execute_table_task(
        self, task: TargetRetrievalTask, top_k: int = 3
    ) -> TargetRetrievalResult:
        """Execute targeted table retrieval matching cells, rows, and candidate indicators."""
        file_name = task.source_constraints.get("file_name")
        sheet_name = task.source_constraints.get("sheet_name")
        target = task.target
        cand_target = task.extra.get("candidate_target") or ""
        row_target = task.extra.get("row") or ""
        col_target = task.extra.get("column") or ""

        evidence: list[SearchResult] = []

        # 1. High-precision SQL Direct Match via Title / Sheet / Row / Metric
        if self.db_path.exists():
            matched_titles = find_matching_table_titles(
                self.db_path, file_name, sheet_name
            )
            conn = sqlite3.connect(self.db_path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            try:
                # Build target search conditions
                terms_to_match = [t for t in (cand_target, row_target, col_target, target) if t]
                for title in matched_titles:
                    where_clauses = ["chunk_type='table'", "title = ?"]
                    params: list[Any] = [title]

                    if sheet_name:
                        clean_sheet = sheet_name.replace("（月度）", "").replace("(月度)", "").replace("（季度）", "").replace("(季度)", "").strip()
                        where_clauses.append("sheet_name LIKE ?")
                        params.append(f"%{clean_sheet}%")

                    # Match specific candidate or operand row
                    match_term = cand_target or row_target
                    if match_term:
                        where_clauses.append("(text LIKE ? OR metadata_json LIKE ?)")
                        params.append(f"%{match_term}%")
                        params.append(f"%{match_term}%")

                    sql = f"SELECT * FROM chunks WHERE {' AND '.join(where_clauses)} LIMIT ?"
                    params.append(top_k * 2)
                    rows = cursor.execute(sql, tuple(params)).fetchall()

                    for r in rows:
                        meta = json.loads(r["metadata_json"]) if r["metadata_json"] else {}
                        meta["matched_target_task"] = task.task_id
                        source_info = SourceInfo(
                            doc_id=r["doc_id"] or "",
                            title=r["title"] or "",
                            issuer=r["issuer"] or "",
                            publish_date=r["publish_date"] or "",
                            section_path=r["section_path"] or "",
                            clause_no=r["clause_no"] or "",
                            sheet_name=r["sheet_name"] or "",
                            table_name=r["table_name"] or "",
                        )
                        sr = SearchResult(
                            chunk_id=r["chunk_id"],
                            chunk_type=r["chunk_type"],
                            score=100.0,
                            text=r["text"],
                            source=source_info,
                            metadata=meta,
                        )
                        if not any(e.chunk_id == sr.chunk_id for e in evidence):
                            evidence.append(sr)
            finally:
                conn.close()

        # 2. Hybrid Reader Search Fallback/Enrichment
        if len(evidence) < top_k:
            query_str = f"{file_name or ''} {target}".strip()
            filters = {"title": file_name} if file_name else {}
            reader_results = self.reader.search(
                query_str,
                top_k=top_k,
                chunk_type="table",
                filters=filters,
                rerank=True,
            )
            for sr in reader_results:
                if not any(e.chunk_id == sr.chunk_id for e in evidence):
                    sr.metadata["matched_target_task"] = task.task_id
                    evidence.append(sr)

        status = "SUCCESS" if evidence else "NO_EVIDENCE"
        return TargetRetrievalResult(
            task_id=task.task_id,
            target=task.target,
            status=status,
            evidence=evidence[:top_k],
            diagnostics={"candidate_count": len(evidence)},
        )

    def _execute_fact_choice_task(
        self, task: TargetRetrievalTask, top_k: int = 3
    ) -> TargetRetrievalResult:
        """Execute discrete fact retrieval for a single choice option claim/sub-claims."""
        doc_name = task.source_constraints.get("document_name")
        filters = {"title": doc_name} if doc_name else {}

        evidence: list[SearchResult] = []

        # If option contains multiple sub-claims (FACT_MULTI_CHOICE paired claims)
        if task.sub_targets and len(task.sub_targets) > 1:
            for sub_claim in task.sub_targets:
                sc_res = self.reader.search(
                    sub_claim,
                    top_k=2,
                    filters=filters,
                    rerank=True,
                )
                for sr in sc_res[:2]:
                    if not any(e.chunk_id == sr.chunk_id for e in evidence):
                        sr.metadata["matched_target_task"] = task.task_id
                        sr.metadata["matched_sub_claim"] = sub_claim
                        evidence.append(sr)
        else:
            claim_res = self.reader.search(
                task.target,
                top_k=top_k,
                filters=filters,
                rerank=True,
            )
            for sr in claim_res:
                sr.metadata["matched_target_task"] = task.task_id
                evidence.append(sr)

        status = "SUCCESS" if evidence else "NO_EVIDENCE"
        return TargetRetrievalResult(
            task_id=task.task_id,
            target=task.target,
            status=status,
            evidence=evidence,
            diagnostics={"candidate_count": len(evidence)},
        )

    def _execute_direct_fact_task(
        self, task: TargetRetrievalTask, top_k: int = 5
    ) -> TargetRetrievalResult:
        """Execute standard direct fact retrieval."""
        doc_name = task.source_constraints.get("document_name")
        filters = {"title": doc_name} if doc_name else {}
        evidence = self.reader.search(
            task.target,
            top_k=top_k,
            filters=filters,
            rerank=True,
        )
        for sr in evidence:
            sr.metadata["matched_target_task"] = task.task_id

        status = "SUCCESS" if evidence else "NO_EVIDENCE"
        return TargetRetrievalResult(
            task_id=task.task_id,
            target=task.target,
            status=status,
            evidence=evidence,
            diagnostics={"candidate_count": len(evidence)},
        )

    def _merge_results(
        self, results: list[TargetRetrievalResult]
    ) -> list[SearchResult]:
        """Deduplicate and consolidate discrete target evidence into a unified evidence list."""
        merged: list[SearchResult] = []
        seen_ids: set[str] = set()

        for res in results:
            for item in res.evidence:
                if item.chunk_id not in seen_ids:
                    seen_ids.add(item.chunk_id)
                    merged.append(item)

        return merged


multi_target_retriever = MultiTargetRetriever()

__all__ = [
    "MultiTargetRetriever",
    "multi_target_retriever",
    "find_matching_table_titles",
]
